### PR TITLE
A few fixes (changes in Mojolicious and DBIX::Class)

### PR DESCRIPTION
**Pull request by bjoernfan**
DBIX::Class has deprecated one thing, and Mojolicious development has also moved forward. Here's a few patches!

### CODE REVIEW

**Comment by bjoernfan** [comment]
It looks like Travis hasn't been able to build this project for a long time... I haven't used Travis before, but I'd guess it would work better if we updated the dependencies in Makefile.PL as well.

```
    'Mojolicious'              => '2.98',
```

Not sure what version you want this project to work against, so I'll leave that up to you. :)

**Comment by tempire** [comment]
I was never able to get MojoExample running well on Travis; I lost interest before it ever turned green.

**Comment by bjoernfan** [comment]
The first set of patches still apply, though. The Makefile.PL thing was just a wild guess that apparently wasn't enough.

Can I may ask; What's the ambition of this project? I think a example like this is very valuable, and if you accept patches I can supply a few more. Maybe I can make the tests pass.

**Comment by davehorner** [comment]
a useful patch will resolve the issues in t/blogs.t

I get the same errors when I run 'make test' locally.  
If you have any ideas, they should be testable locally.
Not sure what to say about these failures myself....still coming up to speed.

Thanks.
--dave
---- from travis CI last failure ----

```
t/blogs.t ... 1/? 
#   Failed test 'exact match for selector "li\#hello_ > h2 > a"'
#   at t/blogs.t line 17.
#          got: ''
#     expected: 'Hello!'
#   Failed test 'exact match for selector "li\#hello_ > h2 > a"'
#   at t/blogs.t line 26.
#          got: ''
#     expected: 'Hello!'
#   Failed test 'exact match for selector "li\#non_tech_2 > h2 > a"'
#   at t/blogs.t line 26.
#          got: ''
#     expected: 'non-tech 2'
#   Failed test 'exact match for selector "li\#tech > h2 > a"'
#   at t/blogs.t line 32.
#          got: ''
#     expected: 'Tech'
#   Failed test 'exact match for selector "li\#hello_ > h2 > a"'
#   at t/blogs.t line 36.
#          got: ''
#     expected: 'Hello!'
#   Failed test 'exact match for selector "li\#non_tech_2 > h2 > a"'
#   at t/blogs.t line 36.
#          got: ''
#     expected: 'non-tech 2'
#   Failed test 'exact match for selector "li\#tech > h2 > a"'
#   at t/blogs.t line 36.
#          got: ''
#     expected: 'Tech'
# Looks like you failed 7 tests of 28.
t/blogs.t ... Dubious, test returned 7 (wstat 1792, 0x700)
Failed 7/28 subtests 
t/home.t .... ok
t/photos.t .. ok
Test Summary Report
-------------------
t/blogs.t (Wstat: 1792 Tests: 28 Failed: 7)
  Failed tests:  8, 16-17, 22, 26-28
  Non-zero exit status: 7
Files=3, Tests=57,  5 wallclock secs ( 0.04 usr  0.01 sys +  3.37 cusr  0.30 csys =  3.72 CPU)
Result: FAIL
Failed 1/3 test programs. 7/57 subtests failed.
make: *** [test_dynamic] Error 255
```

**Comment by jberger** [comment]
This issue was fixed by my changes in #9

**Comment by tempire** [comment]
Apologies to anyone that submitted previous pull requests - I really wasn't paying attention. @jberger  nagged me about it in IRC, and as such, his pull request was accepted.

**Pull request closed without merging**
